[package]
name = "kff"
version = "0.1.0"
description = "Kmer File Format rust parser"

authors = ["Pierre Marijon <pierre.marijon@hhu.de>"]

repository = "https://github.com/Kmer-File-Format/kff-rust-api"
homepage = "https://github.com/Kmer-File-Format/kff-rust-api"
documentation = "https://github.com/Kmer-File-Format/kff-rust-api"

license = "AGPL"

edition = "2018"

[lib]
name = "kff"
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
thiserror = "1"
byteorder = "1"
itertools = "0.9"
bitvec    = "0.20"